#server:
#  port: 8082
#  servlet:
#    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: ead-config-server
#  datasource:
#    url: jdbc:postgresql://localhost:5432/ead-course-v2
#    username: postgres
#    password: 22100932
#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      jdbc:
#        lob.non-contextual-creation: true
#    properties:
#      hibernate:
#        show_sql: true
#
#  output:
#    ansi:
#      enabled: always
#  rabbitmq:
#    addresses: amqps://pyfxikhf:UKpmwpsZObUDfm8OnN39g3tVxc6PK87i@woodpecker.rmq.cloudamqp.com/pyfxikhf
#
#logging:
#  level:
#    com.ead: TRACE
#    root: INFO
#    org.springframework.web: DEBUG
#    org.hibernate: INFO
#
#ead:
#  api:
#    url:
#      authuser: 'http://ead-authuser-service/ead-authuser'
#  broker:
#    exchange:
#      userEventExchange: ead.userevent
#    queue:
#      userEventQueue:
#        name: ead.userevent.course
#
#eureka:
#  client:
#    service-url:
#      defaultZone: 'http://localhost:8761/eureka'
#  instance:
#    hostname: localhost